services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cicispizzadb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user
    ports:
      - "3307:3306" # 3307 trên máy host ánh xạ tới 3306 trong container
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"   # Port cho giao tiếp ứng dụng
      - "15672:15672" # Port cho giao diện quản lý web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:8.0
    container_name: redis_container
    restart: always
    environment:
      REDIS_PASSWORD: yourpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: hoanle2018/be-restaurant-food-order
    # build: .
    container_name: be-foodorder_container
    restart: always
    depends_on:
      - mysql
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST} # Host cho MySQL trong Docker
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST} # Host cho Redis trong Docker
      REDIS_PORT: ${REDIS_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST} # Host cho RabbitMQ trong Docker
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}

volumes:
  mysql_data:
  redis_data:
